name: Task
description: A template for creating detailed tasks with all necessary information.
title: "[Task] "
labels: 
  - task
  - enhancement
assignees:
  - ''

body:
  - type: markdown
    attributes:
      value: |
        ## Task

  - type: input
    id: task_title
    attributes:
      label: Title
      description: Briefly describe the purpose of the task.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be done to complete this task.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level.
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: List the sub-tasks required for this task.
      options:
        - label: Sub-task 1
        - label: Sub-task 2
        - label: Sub-task 3

  - type: input
    id: epic_reference
    attributes:
      label: Epic Reference
      description: Link to the associated Epic or Story.
    validations:
      required: false
